.github/workflows/release.yaml: integrate a full tools release
Signed-off-by: akarin <i@akarin.info>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -44,6 +44,20 @@ jobs:
       run: |
         msbuild.exe OKEGui/OKEGui.sln /nologo /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
 
+    - name: Integrate tools pack from previous release
+      shell: bash
+      run: |
+        set -ex
+        curl -s -o tools.zip -L https://github.com/vcb-s/OKEGui/releases/download/7.3/OKEGui_v7.3.zip
+        7z x -otmp tools.zip
+        # clean up unnecessary files
+        rm -f tmp/OKEGui/tools/mkvtoolnix/cache/fileIdentifier/*
+        # tweak mkvtoolnix setting
+        sed -i -e 's|chapterNameTemplate=.*|chapterNameTemplate=Chapter <NUM:2>|g' tmp/OKEGui/tools/mkvtoolnix/mkvtoolnix-gui.ini
+        # integrate into release
+        mv tmp/OKEGui/tools "./OKEGui/OKEGui/bin/Release/"
+        rm -rf tmp
+
     - name: Integrate eac3to-wrapper
       shell: bash
       run: |
